application: sample-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  login: admin
  script: main.application

- url: /.*
  script: main.application

libraries:
- name: django
  version: "1.5"
- name: PIL
  version: "1.1.7"  
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'core.settings'
